import { RecruitItem } from '@type/recruit';

export const recruitItemDummy: RecruitItem[] = [
  {
    id: 1,
    city: '서울시',
    source: '중랑구',
    title: '지원 공고 제목1',
    isLiked: true,
    likedNum: 153,
    target: '소상공인, 자영업자',
    startDate: '25.01.01',
    endDate: '26.01.01',
  },
  {
    id: 2,
    city: '서울시',
    source: '성북구',
    title: '지원 공고 제목2',
    isLiked: false,
    likedNum: 1053,
    target: '소상공인, 자영업자',
    startDate: '25.01.01',
    endDate: '26.01.01',
  },
  {
    id: 3,
    city: '서울시',
    source: '송파구',
    title: '지원 공고 제목3',
    isLiked: false,
    likedNum: 536,
    target: '소상공인, 자영업자',
    startDate: '25.01.01',
    endDate: '26.01.01',
  },
  {
    id: 4,
    city: '서울시',
    source: '강남구',
    title: '지원 공고 제목4',
    isLiked: true,
    likedNum: 72,
    target: '소상공인, 자영업자',
    startDate: '25.01.01',
    endDate: '26.01.01',
  },
  {
    id: 5,
    city: '서울시',
    source: '중랑구',
    title: '지원 공고 제목5',
    isLiked: true,
    likedNum: 2,
    target: '소상공인, 자영업자',
    startDate: '25.01.01',
    endDate: '26.01.01',
  },
];
